### ISSUE TITLE
Allow local docker file as well as release docker file

### ISSUE THREAD

**Issue by joe-getcouragenow** [dnys1/grpc_demo#2]
Here is a great example:

https://github.com/pion/ion/blob/master/docker-compose.yml
- Note how it uses the local docker: https://github.com/pion/ion/blob/master/docker-compose.yml#L7

https://github.com/pion/ion/blob/master/docker-compose.stable.yml
- Note how it uses docker hub images

**Comment by dnys1** [comment]
Well, that was a fun little rabbit hole. Thanks for sharing!

Migrated to separate Docker compose files.
